[build]
functions="functions"
base="/"
command="npm build"
[dev]
functions="functions"
base="/"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
[[redirects]]
  from = "favicon.ico"
  to = "/icons/favicon.ico"
  status = 200
  force = true